name       : powerline
version    : '2.6'
release    : 4
source     :
    - https://github.com/powerline/powerline/archive/2.6.tar.gz : c108f11fe10dc910febb94b87d3abded85d4363fb950366a9e30282b9ba7c272
license    : MIT
component  : system.utils
summary    : Powerline vim plugin and shell prompts
description: |
    Powerline is a statusline plugin for vim, and provides statuslines and prompts for several other applications, including zsh, bash, tmux, IPython, Awesome and Qtile.
builddeps  :
    - python-setuptools
    - python-sphinx
build      : |
    pushd docs
    %make man
    popd
    %python_setup
install    : |
    # install man-files
    install -d -m 0755 $installdir/usr/share/man/man1
    install -D -m 0644 $workdir/docs/_build/man/*.1 $installdir/usr/share/man/man1/
    # Install systemd service
    install -Dm00644 $pkgfiles/powerline-daemon.service $installdir/%libdir%/systemd/system/powerline-daemon.service
    # Copy sane defaults configs
    install -Dm00644 $pkgfiles/config.json $installdir/usr/lib/python2.7/site-packages/powerline/config_files/config.json
    %python_install
