name       : powerline
version    : 2.3
release    : 1
source     :
    - https://codeload.github.com/powerline/powerline/tar.gz/2.3 : c65762df4733afed585af722978d24bc555fbbabb8ae707e4e525dff6412de5f
license    : MIT
summary    : Powerline vim plugin and shell prompts
description: |
    Powerline is a statusline plugin for vim, and provides statuslines and prompts for several other applications, including zsh, bash, tmux, IPython, Awesome and Qtile.
builddeps  :
    - python-setuptools
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
