name       : powerline
version    : 2.5.2
release    : 3
source     :
    - https://github.com/powerline/powerline/archive/2.5.2.tar.gz : 3ffb2374098a5ed1b1c232070c808b6ae08b80c3859031710f7793ffa5b89918
license    : MIT
component  : system.utils
summary    : Powerline vim plugin and shell prompts
description: |
    Powerline is a statusline plugin for vim, and provides statuslines and prompts for several other applications, including zsh, bash, tmux, IPython, Awesome and Qtile.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
