name       : powerline
version    : 2.7
release    : 9
source     :
    - https://github.com/powerline/powerline/archive/2.7.tar.gz : 45173a3fd583e60d1c6752b00b67e7f9c342285ec57a57abc1cd6d785d1632c0
license    : MIT
component  : system.utils
summary    : Powerline vim plugin and shell prompts
description: |
    Powerline is a statusline plugin for vim, and provides statuslines and prompts for several other applications, including zsh, bash, tmux, IPython, Awesome and Qtile.
builddeps  :
    - python-sphinx
build      : |
    %make -C docs man
    %python3_setup
install    : |
    # install man-files
    install -Dm00644 powerline-${version}/docs/_build/man/*.1 -t $installdir/usr/share/man/man1/
    # Install systemd service
    install -Dm00644 $pkgfiles/powerline-daemon.service $installdir/%libdir%/systemd/system/powerline-daemon.service
    # Copy sane defaults configs
    install -Dm00644 $pkgfiles/config.json $installdir/usr/lib/python3.7/site-packages/powerline/config_files/config.json
    %python3_install
